replicaCount: 1

image:
  repository: jetbrains/teamcity-server
  tag: latest
  pullPolicy: IfNotPresent
  name: teamcity-server-instance

service:
  type: ClusterIP
  port: 8111

persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
  logs:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi

resources: {}
