replicaCount: 1
name: team-city-app
image:
  repository: jetbrains/teamcity-server
  tag: latest
  pullPolicy: IfNotPresent
  name: teamcity-server-instance

service:
  type: NodePort
  port: 8111

persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
  logs:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi

resources: {}
