---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "teamcity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teamcity.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8111
              name: http
          volumeMounts:
            - name: data
              mountPath: /data/teamcity_server/datadir
            - name: logs
              mountPath: /opt/teamcity/logs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "teamcity.fullname" . }}-data
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "teamcity.fullname" . }}-logs
