apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcity.fullname" . }}-data
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcity.fullname" . }}-logs
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
